language: node_js
node_js:
  - "8"
script:
 - echo "Beam me up, Scotty"
install:
  - npm install -g firebase-tools
after_success:
  - firebase deploy --project api.carlosanjos-dev --token $FIREBASE_TOKEN