language: node_js
node_js:
  - "stable"
script:
 - echo "Beam me up, Scotty"
install:
  - npm install -g firebase-tools
  - npm run build
after_success:
  - firebase deploy --project carlosanjos-dev --token $FIREBASE_TOKEN